DROP TABLE IF EXISTS Employee;
DROP TABLE IF EXISTS Vacation;

CREATE TABLE IF NOT EXISTS Employee (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(250) NOT NULL,
    surname VARCHAR(250) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS Vacation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY,
    employee_id INT NOT NULL,
    date_from DATE NOT NULL,
    date_to DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (employee_id) REFERENCES Employee(id) ON DELETE CASCADE
);

INSERT INTO Employee (name, surname) VALUES
  ('Anica', 'Dobra'),
  ('Branka', 'Katic'),
  ('Tereza', 'Kesofija'),
  ('Natasa', 'Markovic');

INSERT INTO Vacation (employee_id, date_from, date_to, status) VALUES
  (1, '2021-03-01', '2021-03-05', 'SUBMITTED'),
  (2, '2021-04-01', '2021-04-05', 'SUBMITTED'),
  (2, '2021-05-01', '2021-05-05', 'SUBMITTED'),
  (3, '2021-06-01', '2021-06-05', 'SUBMITTED'),
  (4, '2021-07-01', '2021-07-05', 'SUBMITTED');
